#!/usr/bin/env bash
#This script displays "Best School" ten times using the while loop.
#+print "Hi" on 9th iteration.

i=0
while (($i<10))
do
	echo "Best School"
	if [ $i = 8 ]; then
		echo "Hi"
	fi
	i=$((i+1))
done
