#!/usr/bin/env bash
#Displays the content of the current directory in a list format where only the part of the name after the first dash is displayed

list=$(ls)
for item in $list
do
	echo "$item" | cut -d '-' -f2
done
